name: KoboToolbox Sync

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:     # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pytz

      - name: Run KoboToolbox Sync
        env:
          KOBO_API_TOKEN: ${{ secrets.KOBO_API_TOKEN }}
        run: python kobo_sync.py

      - name: Verify files to commit
        run: |
          echo "Files in directory:"
          ls -la
          echo "CSV files:"
          ls *.csv || echo "No CSV files found"
          echo "Git status:"
          git status

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated sync: ${{ github.run_number }}"
          branch: main
          add: "*.csv"
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          token: ${{ secrets.GH_PAT }}
          skip_fetch: true
          skip_checkout: false
          file_pattern: "*.csv"
