name: KoboToolbox Sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
          persist-credentials: true  # Critical for push access

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pytz

      - name: Run KoboToolbox Sync
        env:
          KOBO_API_TOKEN: ${{ secrets.KOBO_API_TOKEN }}
        run: python kobo_sync.py

      - name: Verify CSV exists
        run: |
          echo "Current directory: $(pwd)"
          echo "Files:"
          ls -la
          echo "CSV files:"
          ls *.csv || echo "No CSV files found"
          echo "File content sample:"
          head -n 3 *.csv || echo "No CSV content"

      - name: Commit and push changes
        run: |
          # Configure git identity
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Add all CSV files
          git add *.csv
          
          # Check if there are changes
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            # Commit changes
            git commit -m "Automated sync: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            
            # Push changes
            git push origin HEAD:${{ github.ref }}
            echo "Changes pushed successfully"
          fi
        env:
          # Use the same token for authentication
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
