name: KoboToolbox Sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pytz

      - name: Debug - Show environment info
        run: |
          echo "Python path: $(which python)"
          echo "Python version: $(python --version)"
          echo "Repo: $GITHUB_REPOSITORY"

      - name: Run KoboToolbox Sync
        env:
          KOBO_API_TOKEN: ${{ secrets.KOBO_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "KOBO_TOKEN length: ${#KOBO_API_TOKEN}"
          echo "GH_TOKEN length: ${#GITHUB_TOKEN}"
          python -c "import os; print('Current dir:', os.listdir())"
          python kobo_sync.py
